<?php

/*
 * Auto-generated by libasynql-def
 * Created from bank.mysql.sql, core.mysql.sql, loan.mysql.sql, player.mysql.sql, bank.sqlite.sql, core.sqlite.sql, loan.sqlite.sql, player.sqlite.sql
 */

declare(strict_types=1);

namespace DHMO\XialotEcon\Database;

final class Queries{
	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:182
	 */
	public const XIALOTECON_ACCOUNT_INIT_TABLE = "xialotecon.account.init_table";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:208
	 *
	 * <h3>Variables</h3>
	 * - <code>:ownerType</code> string, required in core.mysql.sql
	 * - <code>:ownerName</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_LOAD_BY_OWNER = "xialotecon.account.load.by_owner";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:236
	 *
	 * <h3>Variables</h3>
	 * - <code>:ownerType</code> string, required in core.mysql.sql
	 * - <code>:ownerName</code> string, required in core.mysql.sql
	 * - <code>:currency</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_LOAD_BY_OWNER_CURRENCY = "xialotecon.account.load.by_owner_currency";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:251
	 *
	 * <h3>Variables</h3>
	 * - <code>:accountTypes</code> string non-empty list, required in core.mysql.sql
	 * - <code>:ownerType</code> string, required in core.mysql.sql
	 * - <code>:ownerName</code> string, required in core.mysql.sql
	 * - <code>:currency</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_LOAD_BY_OWNER_CURRENCY_TYPE = "xialotecon.account.load.by_owner_currency_type";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:222
	 *
	 * <h3>Variables</h3>
	 * - <code>:accountTypes</code> string non-empty list, required in core.mysql.sql
	 * - <code>:ownerType</code> string, required in core.mysql.sql
	 * - <code>:ownerName</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_LOAD_BY_OWNER_TYPE = "xialotecon.account.load.by_owner_type";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:195
	 *
	 * <h3>Variables</h3>
	 * - <code>:xoid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_LOAD_BY_XOID = "xialotecon.account.load.by_xoid";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:269
	 *
	 * <h3>Variables</h3>
	 * - <code>:limit</code> int, required in core.mysql.sql
	 * - <code>:time</code> float, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_OBSOLETE_DELETE_LIMITED = "xialotecon.account.obsolete.delete.limited";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:275
	 *
	 * <h3>Variables</h3>
	 * - <code>:time</code> float, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_OBSOLETE_DELETE_UNLIMITED = "xialotecon.account.obsolete.delete.unlimited";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:260
	 *
	 * <h3>Variables</h3>
	 * - <code>:time</code> float, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_OBSOLETE_FIND = "xialotecon.account.obsolete.find";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:302
	 *
	 * <h3>Variables</h3>
	 * - <code>:xoid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_TOUCH = "xialotecon.account.touch";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:295
	 *
	 * <h3>Variables</h3>
	 * - <code>:accountType</code> string, required in core.mysql.sql
	 * - <code>:ownerType</code> string, required in core.mysql.sql
	 * - <code>:ownerName</code> string, required in core.mysql.sql
	 * - <code>:currency</code> string, required in core.mysql.sql
	 * - <code>:balance</code> float, required in core.mysql.sql
	 * - <code>:xoid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_UPDATE_HYBRID = "xialotecon.account.update.hybrid";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:87
	 *
	 * <h3>Variables</h3>
	 * - <code>:accountId</code> string, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_FIND_BY_ACCOUNT_CONSTANT_DIFF = "xialotecon.bank.interest.find.by_account.constant_diff";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:77
	 *
	 * <h3>Variables</h3>
	 * - <code>:accountId</code> string, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_FIND_BY_ACCOUNT_CONSTANT_RATIO = "xialotecon.bank.interest.find.by_account.constant_ratio";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:109
	 *
	 * <h3>Variables</h3>
	 * - <code>:interestId</code> string, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_FIND_BY_XOID_CONSTANT_DIFF = "xialotecon.bank.interest.find.by_xoid.constant_diff";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:99
	 *
	 * <h3>Variables</h3>
	 * - <code>:interestId</code> string, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_FIND_BY_XOID_CONSTANT_RATIO = "xialotecon.bank.interest.find.by_xoid.constant_ratio";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:29
	 */
	public const XIALOTECON_BANK_INTEREST_INIT_CONSTANT_DIFF = "xialotecon.bank.interest.init.constant_diff";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:17
	 */
	public const XIALOTECON_BANK_INTEREST_INIT_CONSTANT_RATIO = "xialotecon.bank.interest.init.constant_ratio";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:45
	 *
	 * <h3>Variables</h3>
	 * - <code>:interestId</code> string, required in bank.mysql.sql
	 * - <code>:accountId</code> string, required in bank.mysql.sql
	 * - <code>:period</code> float, required in bank.mysql.sql
	 * - <code>:diff</code> float, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_INSERT_CONSTANT_DIFF = "xialotecon.bank.interest.insert.constant_diff";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:38
	 *
	 * <h3>Variables</h3>
	 * - <code>:interestId</code> string, required in bank.mysql.sql
	 * - <code>:accountId</code> string, required in bank.mysql.sql
	 * - <code>:period</code> float, required in bank.mysql.sql
	 * - <code>:ratio</code> float, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_INSERT_CONSTANT_RATIO = "xialotecon.bank.interest.insert.constant_ratio";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:65
	 *
	 * <h3>Variables</h3>
	 * - <code>:lastApplied</code> timestamp, required in bank.mysql.sql
	 * - <code>:interestId</code> string, required in bank.mysql.sql
	 * - <code>:period</code> float, required in bank.mysql.sql
	 * - <code>:diff</code> float, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_UPDATE_CONSTANT_DIFF = "xialotecon.bank.interest.update.constant_diff";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/bank.mysql.sql:56
	 *
	 * <h3>Variables</h3>
	 * - <code>:lastApplied</code> timestamp, required in bank.mysql.sql
	 * - <code>:interestId</code> string, required in bank.mysql.sql
	 * - <code>:period</code> float, required in bank.mysql.sql
	 * - <code>:ratio</code> float, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_UPDATE_CONSTANT_RATIO = "xialotecon.bank.interest.update.constant_ratio";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:134
	 */
	public const XIALOTECON_CURRENCY_INIT_TABLE = "xialotecon.currency.init_table";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:153
	 *
	 * <h3>Variables</h3>
	 * - <code>:xoid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_CURRENCY_LOAD_BY_XOID = "xialotecon.currency.load.by_xoid";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:142
	 */
	public const XIALOTECON_CURRENCY_LOAD_ALL = "xialotecon.currency.load_all";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:167
	 *
	 * <h3>Variables</h3>
	 * - <code>:symbolBefore</code> string, required in core.mysql.sql
	 * - <code>:symbolAfter</code> string, required in core.mysql.sql
	 * - <code>:xoid</code> string, required in core.mysql.sql
	 * - <code>:name</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_CURRENCY_UPDATE_HYBRID = "xialotecon.currency.update.hybrid";

	/**
	 * <i>(Description from resources/mysql/core.mysql.sql)</i>
	 *
	 * Selects <code>[{"result": result}]</code>, where result is a boolean indicating whether we are the duty server.
	 *
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:115
	 *
	 * <h3>Variables</h3>
	 * - <code>:serverId</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_DATA_MODEL_DUTY_ACQUIRE = "xialotecon.data_model.duty.acquire";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:109
	 */
	public const XIALOTECON_DATA_MODEL_DUTY_INIT_FUNC = "xialotecon.data_model.duty.init.func";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:68
	 */
	public const XIALOTECON_DATA_MODEL_DUTY_INIT_TABLE = "xialotecon.data_model.duty.init.table";

	/**
	 * <i>(Description from resources/mysql/core.mysql.sql)</i>
	 *
	 * Maintains the duty lock. Only run this query if you are sure that you have acquired the duty lock.
	 * the serverId parameter is to produce an accurate changed-rows result so that we can check if we have lost the duty lock.
	 *
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:122
	 *
	 * <h3>Variables</h3>
	 * - <code>:serverId</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_DATA_MODEL_DUTY_MAINTAIN = "xialotecon.data_model.duty.maintain";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:56
	 *
	 * <h3>Variables</h3>
	 * - <code>:persistence</code> float, required in core.mysql.sql
	 */
	public const XIALOTECON_DATA_MODEL_FEED_CLEAR = "xialotecon.data_model.feed.clear";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:42
	 */
	public const XIALOTECON_DATA_MODEL_FEED_FETCH_FIRST = "xialotecon.data_model.feed.fetch_first";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:51
	 *
	 * <h3>Variables</h3>
	 * - <code>:lastMaxUpdate</code> int, required in core.mysql.sql
	 * - <code>:server</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_DATA_MODEL_FEED_FETCH_NEXT = "xialotecon.data_model.feed.fetch_next";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:31
	 */
	public const XIALOTECON_DATA_MODEL_FEED_INIT = "xialotecon.data_model.feed.init";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:38
	 *
	 * <h3>Variables</h3>
	 * - <code>:server</code> string, required in core.mysql.sql
	 * - <code>:xoid</code> string, required in core.mysql.sql
	 * - <code>:type</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_DATA_MODEL_FEED_UPDATE = "xialotecon.data_model.feed.update";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/loan.mysql.sql:33
	 */
	public const XIALOTECON_LOAN_DUTY_GLOBAL_COMPOUND = "xialotecon.loan.duty.global_compound";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/loan.mysql.sql:22
	 */
	public const XIALOTECON_LOAN_INIT_LOANS = "xialotecon.loan.init.loans";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:10
	 */
	public const XIALOTECON_METADATA_CREATE = "xialotecon.metadata.create";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:14
	 *
	 * <h3>Variables</h3>
	 * - <code>:version</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_METADATA_DECLARE_VERSION = "xialotecon.metadata.declare_version";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:17
	 */
	public const XIALOTECON_METADATA_SELECT_VERSION = "xialotecon.metadata.select_version";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/player.mysql.sql:10
	 */
	public const XIALOTECON_PLAYER_LOGIN_INIT = "xialotecon.player.login.init";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/player.mysql.sql:15
	 *
	 * <h3>Variables</h3>
	 * - <code>:name</code> string, required in player.mysql.sql
	 */
	public const XIALOTECON_PLAYER_LOGIN_TOUCH_INSERT = "xialotecon.player.login.touch.insert";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/player.mysql.sql:21
	 *
	 * <h3>Variables</h3>
	 * - <code>:name</code> string, required in player.mysql.sql
	 */
	public const XIALOTECON_PLAYER_LOGIN_TOUCH_UPDATE = "xialotecon.player.login.touch.update";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/player.mysql.sql:28
	 *
	 * <h3>Variables</h3>
	 * - <code>:name</code> string, required in player.mysql.sql
	 */
	public const XIALOTECON_PLAYER_LOGIN_WHEN = "xialotecon.player.login.when";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/player.mysql.sql:36
	 *
	 * <h3>Variables</h3>
	 * - <code>:accountIds</code> string non-empty list, required in player.mysql.sql
	 */
	public const XIALOTECON_PLAYER_STATS_BALANCE_GROUPED_SUM = "xialotecon.player.stats.balance.grouped_sum";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:317
	 */
	public const XIALOTECON_TRANSACTION_INIT_TABLE = "xialotecon.transaction.init_table";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:330
	 *
	 * <h3>Variables</h3>
	 * - <code>:xoid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_TRANSACTION_LOAD_BY_XOID = "xialotecon.transaction.load.by_xoid";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/core.mysql.sql:349
	 *
	 * <h3>Variables</h3>
	 * - <code>:transactionType</code> string, required in core.mysql.sql
	 * - <code>:sourceReduction</code> float, required in core.mysql.sql
	 * - <code>:targetAddition</code> float, required in core.mysql.sql
	 * - <code>:source</code> string, required in core.mysql.sql
	 * - <code>:target</code> string, required in core.mysql.sql
	 * - <code>:xoid</code> string, required in core.mysql.sql
	 * - <code>:date</code> timestamp, required in core.mysql.sql
	 */
	public const XIALOTECON_TRANSACTION_UPDATE_HYBRID = "xialotecon.transaction.update.hybrid";

}
