<?php

/*
 * Auto-generated by libasynql-def
 * Created from bank.mysql.sql, core.mysql.sql, player.mysql.sql, bank.sqlite.sql, core.sqlite.sql, player.sqlite.sql
 */

declare(strict_types=1);

namespace DHMO\XialotEcon\Database;

final class Queries{
	/**
	 * <code>xialotecon.account.init_table</code>
	 *
	 * Defined in core.mysql.sql:93
	 */
	public const XIALOTECON_ACCOUNT_INIT_TABLE = "xialotecon.account.init_table";

	/**
	 * <code>xialotecon.account.load.by_uuid</code>
	 *
	 * Defined in core.mysql.sql:105
	 *
	 * Variables:
	 * - <code>:uuid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_LOAD_BY_UUID = "xialotecon.account.load.by_uuid";

	/**
	 * <code>xialotecon.account.touch</code>
	 *
	 * Defined in core.mysql.sql:130
	 *
	 * Variables:
	 * - <code>:uuid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_TOUCH = "xialotecon.account.touch";

	/**
	 * <code>xialotecon.account.update.hybrid</code>
	 *
	 * Defined in core.mysql.sql:123
	 *
	 * Variables:
	 * - <code>:accountType</code> string, required in core.mysql.sql
	 * - <code>:ownerType</code> string, required in core.mysql.sql
	 * - <code>:ownerName</code> string, required in core.mysql.sql
	 * - <code>:currency</code> string, required in core.mysql.sql
	 * - <code>:balance</code> float, required in core.mysql.sql
	 * - <code>:uuid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_ACCOUNT_UPDATE_HYBRID = "xialotecon.account.update.hybrid";

	/**
	 * <code>xialotecon.bank.interest.add.constant_diff</code>
	 *
	 * Defined in bank.mysql.sql:41
	 *
	 * Variables:
	 * - <code>:accountId</code> string, required in bank.mysql.sql
	 * - <code>:period</code> float, required in bank.mysql.sql
	 * - <code>:value</code> float, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_ADD_CONSTANT_DIFF = "xialotecon.bank.interest.add.constant_diff";

	/**
	 * <code>xialotecon.bank.interest.add.constant_ratio</code>
	 *
	 * Defined in bank.mysql.sql:35
	 *
	 * Variables:
	 * - <code>:accountId</code> string, required in bank.mysql.sql
	 * - <code>:period</code> float, required in bank.mysql.sql
	 * - <code>:value</code> float, required in bank.mysql.sql
	 */
	public const XIALOTECON_BANK_INTEREST_ADD_CONSTANT_RATIO = "xialotecon.bank.interest.add.constant_ratio";

	/**
	 * <code>xialotecon.bank.interest.init.constant_diff</code>
	 *
	 * Defined in bank.mysql.sql:27
	 */
	public const XIALOTECON_BANK_INTEREST_INIT_CONSTANT_DIFF = "xialotecon.bank.interest.init.constant_diff";

	/**
	 * <code>xialotecon.bank.interest.init.constant_ratio</code>
	 *
	 * Defined in bank.mysql.sql:16
	 */
	public const XIALOTECON_BANK_INTEREST_INIT_CONSTANT_RATIO = "xialotecon.bank.interest.init.constant_ratio";

	/**
	 * <code>xialotecon.currency.init_table</code>
	 *
	 * Defined in core.mysql.sql:45
	 */
	public const XIALOTECON_CURRENCY_INIT_TABLE = "xialotecon.currency.init_table";

	/**
	 * <code>xialotecon.currency.load.by_uuid</code>
	 *
	 * Defined in core.mysql.sql:64
	 *
	 * Variables:
	 * - <code>:uuid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_CURRENCY_LOAD_BY_UUID = "xialotecon.currency.load.by_uuid";

	/**
	 * <code>xialotecon.currency.load_all</code>
	 *
	 * Defined in core.mysql.sql:53
	 */
	public const XIALOTECON_CURRENCY_LOAD_ALL = "xialotecon.currency.load_all";

	/**
	 * <code>xialotecon.currency.update.hybrid</code>
	 *
	 * Defined in core.mysql.sql:78
	 *
	 * Variables:
	 * - <code>:symbolBefore</code> string, required in core.mysql.sql
	 * - <code>:symbolAfter</code> string, required in core.mysql.sql
	 * - <code>:uuid</code> string, required in core.mysql.sql
	 * - <code>:name</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_CURRENCY_UPDATE_HYBRID = "xialotecon.currency.update.hybrid";

	/**
	 * <code>xialotecon.data_model.feed_update</code>
	 *
	 * Defined in core.mysql.sql:21
	 *
	 * Variables:
	 * - <code>:server</code> string, required in core.mysql.sql
	 * - <code>:uuid</code> string, required in core.mysql.sql
	 * - <code>:type</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_DATA_MODEL_FEED_UPDATE = "xialotecon.data_model.feed_update";

	/**
	 * <code>xialotecon.data_model.fetch_first_update</code>
	 *
	 * Defined in core.mysql.sql:25
	 */
	public const XIALOTECON_DATA_MODEL_FETCH_FIRST_UPDATE = "xialotecon.data_model.fetch_first_update";

	/**
	 * <code>xialotecon.data_model.fetch_next_update</code>
	 *
	 * Defined in core.mysql.sql:34
	 *
	 * Variables:
	 * - <code>:lastMaxUpdate</code> int, required in core.mysql.sql
	 * - <code>:server</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_DATA_MODEL_FETCH_NEXT_UPDATE = "xialotecon.data_model.fetch_next_update";

	/**
	 * <code>xialotecon.data_model.init_feed</code>
	 *
	 * Defined in core.mysql.sql:14
	 */
	public const XIALOTECON_DATA_MODEL_INIT_FEED = "xialotecon.data_model.init_feed";

	/**
	 * <code>xialotecon.player.login.init</code>
	 *
	 * Defined in player.mysql.sql:10
	 */
	public const XIALOTECON_PLAYER_LOGIN_INIT = "xialotecon.player.login.init";

	/**
	 * <code>xialotecon.player.login.touch.insert</code>
	 *
	 * Defined in player.mysql.sql:15
	 *
	 * Variables:
	 * - <code>:name</code> string, required in player.mysql.sql
	 */
	public const XIALOTECON_PLAYER_LOGIN_TOUCH_INSERT = "xialotecon.player.login.touch.insert";

	/**
	 * <code>xialotecon.player.login.touch.update</code>
	 *
	 * Defined in player.mysql.sql:21
	 *
	 * Variables:
	 * - <code>:name</code> string, required in player.mysql.sql
	 */
	public const XIALOTECON_PLAYER_LOGIN_TOUCH_UPDATE = "xialotecon.player.login.touch.update";

	/**
	 * <code>xialotecon.player.login.when</code>
	 *
	 * Defined in player.mysql.sql:28
	 *
	 * Variables:
	 * - <code>:name</code> string, required in player.mysql.sql
	 */
	public const XIALOTECON_PLAYER_LOGIN_WHEN = "xialotecon.player.login.when";

	/**
	 * <code>xialotecon.transaction.init_table</code>
	 *
	 * Defined in core.mysql.sql:145
	 */
	public const XIALOTECON_TRANSACTION_INIT_TABLE = "xialotecon.transaction.init_table";

	/**
	 * <code>xialotecon.transaction.load.by_uuid</code>
	 *
	 * Defined in core.mysql.sql:158
	 *
	 * Variables:
	 * - <code>:uuid</code> string, required in core.mysql.sql
	 */
	public const XIALOTECON_TRANSACTION_LOAD_BY_UUID = "xialotecon.transaction.load.by_uuid";

	/**
	 * <code>xialotecon.transaction.update.hybrid</code>
	 *
	 * Defined in core.mysql.sql:177
	 *
	 * Variables:
	 * - <code>:transactionType</code> string, required in core.mysql.sql
	 * - <code>:sourceReduction</code> float, required in core.mysql.sql
	 * - <code>:targetAddition</code> float, required in core.mysql.sql
	 * - <code>:source</code> string, required in core.mysql.sql
	 * - <code>:target</code> string, required in core.mysql.sql
	 * - <code>:uuid</code> string, required in core.mysql.sql
	 * - <code>:date</code> timestamp, required in core.mysql.sql
	 */
	public const XIALOTECON_TRANSACTION_UPDATE_HYBRID = "xialotecon.transaction.update.hybrid";

}
