projects:
  XialotEcon:
    libs:
      - src: poggit/libasynql/libasynql
        version: ^3.0
        epitope: .sha
      - src: SOF3/libglocal/libglocal
        version: 0.1.0
        epitope: .sha
      - src: SOF3/libkinetic/libkinetic
        version: 0.0.1
        epitope: .sha
