---
main: DHMO\XialotEcon\XialotEcon
name: XialotEcon
description: A next-gem economy plugin
website: https://dihydrogen-monixide.github.io/XialotEcon
author: DHMO Team
authors:
- SOFe
- Hittmana
api:
- 3.0.0-ALPHA12
version: 0.0.1
permissions:
  xialotecon:
    default: op
    description: XialotEcon root permission node
    children:
      xialotecon.player:
        default: op
        children:
          xialotecon.player.cash:
            default: op
            children:
              xialotecon.player.cash.deposit:
                default: true
                description: Allows depositing money into cash account directly
              xialotecon.player.cash.withdraw:
                default: true
                description: Allows spending money from cash account directly
          xialotecon.player.bank:
            default: op
            children:
              xialotecon.player.bank.deposit:
                default: true
                description: Allows depositing money into bank account directly
              xialotecon.player.bank.withdraw:
                default: true
                description: Allows spending money from bank account directly
          xialotecon.player.transaction:
            default: op
            description: Permission to carry out transactions
            children:
              xialotecon.player.transaction.pay:
                default: true
                description: Allows paying money to another player through the /pay
                  command
              xialotecon.player.transaction.bank:
                default: op
                children:
                  xialotecon.player.transaction.bank.deposit:
                    default: true
                    description: Allows depositing money from cash to bank
                  xialotecon.player.transaction.bank.withdrawal:
                    default: true
                    description: Allows withdrawing money from bank to cash
          xialotecon.player.loan:
            default: op
            description: Permission to interact with loans
            children:
              xialotecon.player.loan.borrow:
                default: op
                description: Permission to borrow loans
                children:
                  xialotecon.player.loan.borrow.server:
                    default: true
                    description: Allows borrowing loans from the server
                  xialotecon.player.loan.borrow.player:
                    default: true
                    description: Allows borrowing loans from other players
              xialotecon.player.loan.lend:
                default: true
                description: Allows lending loans to other players
          xialotecon.player.analysis:
            default: op
            description: Permission for analysing a player's financial state
            children:
              xialotecon.player.analysis.balance:
                default: op
                description: Permission to check account balance summary by account
                  type
                children:
                  xialotecon.player.analysis.balance.my:
                    default: true
                    description: Allows accessing own balance summary report
                  xialotecon.player.analysis.balance.his:
                    default: op
                    description: Allows accessing others' balance summary report
      xialotecon.admin:
        default: op
...
