<?php

/*
 * libkinetic node ID final class
 *
 * This file is automatically generated by libkinetic-def
 */

declare(strict_types=1);

namespace DHMO\XialotEcon;

final class KineticIds{
	/**
	 * IndexNode &lt;INDEX&gt;
	 */
	public const XIALOTECON = "xialotecon";
	/**
	 * InfoNode &lt;INFO&gt;
	 */
	public const XIALOTECON_ABOUT = "xialotecon.about";
	/**
	 * IndexNode &lt;INDEX&gt;
	 */
	public const XIALOTECON_ADMIN = "xialotecon.admin";
	/**
	 * IndexNode &lt;INDEX&gt;
	 */
	public const XIALOTECON_ADMIN_ANALYTICS = "xialotecon.admin.analytics";
	/**
	 * InfoNode &lt;INFO&gt;
	 */
	public const XIALOTECON_ADMIN_ANALYTICS_BALANCE = "xialotecon.admin.analytics.balance";
	/**
	 * ListNode &lt;LIST&gt;
	 */
	public const XIALOTECON_ADMIN_ANALYTICS_WEALTHLIST = "xialotecon.admin.analytics.wealthList";
	/**
	 * BeforeListNode &lt;BEFORE&gt;
	 */
	public const XIALOTECON_ADMIN_ANALYTICS_WEALTHLIST_BEFORE = "xialotecon.admin.analytics.wealthList.before";
	/**
	 * IndexNode &lt;INDEX&gt;
	 */
	public const XIALOTECON_ADMIN_MODERATION = "xialotecon.admin.moderation";
	/**
	 * ListNode &lt;LIST&gt;
	 */
	public const XIALOTECON_ADMIN_MODERATION_BANKRUPTQUEUE = "xialotecon.admin.moderation.bankruptQueue";
	/**
	 * IndexNode &lt;INDEX&gt;
	 */
	public const XIALOTECON_BANK = "xialotecon.bank";
}
