<?php

/*
 * libglocal message ID constant file
 *
 * This file is automatically generated by libglocal-def
 */

declare(strict_types=1);

namespace DHMO\XialotEcon;

final class Lang{
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>XialotEcon</p>
	 * </blockquote>
	 */
	public const XIALOTECON_MAIN_TITLE = "xialotecon.main.title";
	/**
	 * This is the line displayed in the main menu page.
	 *
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Welcome to XialotEcon!</p>
	 * </blockquote>
	 */
	public const XIALOTECON_MAIN_SYNOPSIS = "xialotecon.main.synopsis";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Staff Tools</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_TITLE = "xialotecon.staff.title";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Hello staff! What would you like to do?</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_SYNOPSIS = "xialotecon.staff.synopsis";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Pending Queues</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_QUEUES_TITLE = "xialotecon.staff.queues.title";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Some pending work to do.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_QUEUES_SYNOPSIS = "xialotecon.staff.queues.synopsis";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Bankruptcy</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_QUEUES_BANKRUPTCY_TITLE = "xialotecon.staff.queues.bankruptcy.title";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Players below are unable to repay debts automatically. Click into each player to view his financial status. Help them liquidate properties and carry out any additional action.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_QUEUES_BANKRUPTCY_SYNOPSIS = "xialotecon.staff.queues.bankruptcy.synopsis";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Global Economy Analytics</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_TITLE = "xialotecon.staff.analytics.title";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Analyze the economy situation in the whole server/network.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_SYNOPSIS = "xialotecon.staff.analytics.synopsis";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Wealthiest Players</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_WEALTH_LIST_TITLE = "xialotecon.staff.analytics.wealth-list.title";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Click into each player to view his financial status.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_WEALTH_LIST_SYNOPSIS = "xialotecon.staff.analytics.wealth-list.synopsis";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>%{error}You don't have permission to view other players' balance.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_WEALTH_LIST_PERMISSION_MESSAGE_HIS = "xialotecon.staff.analytics.wealth-list.permission-message.his";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>display size</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_WEALTH_LIST_LIMIT_ARG_NAME = "xialotecon.staff.analytics.wealth-list.limit.arg-name";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Number of players to display</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_WEALTH_LIST_LIMIT_INPUT_NAME = "xialotecon.staff.analytics.wealth-list.limit.input-name";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Currency weight</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_WEALTH_LIST_CURRENCY_WEIGHT_TITLE = "xialotecon.staff.analytics.wealth-list.currency-weight.title";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Include ${currency.name}?</p>
	 * </blockquote>
	 * <h3>Arguments:</h3>
	 * - `currency.name`: string</li>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_WEALTH_LIST_CURRENCY_WEIGHT_TOGGLE = "xialotecon.staff.analytics.wealth-list.currency-weight.toggle";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Weight:</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_WEALTH_LIST_CURRENCY_WEIGHT_WEIGHT = "xialotecon.staff.analytics.wealth-list.currency-weight.weight";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Balance of ${whose}</p>
	 * </blockquote>
	 * <h3>Arguments:</h3>
	 * - `whose`: string</li>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_BALANCE_TITLE = "xialotecon.staff.analytics.balance.title";
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>TODO</p>
	 * </blockquote>
	 */
	public const XIALOTECON_STAFF_ANALYTICS_BALANCE_CONTENT = "xialotecon.staff.analytics.balance.content";
}
