---
core:
  provider: sqlite
  sqlite:
    path: XialotEcon.db
  mysql:
    host: localhost
    username: root
    password: ""
    schema: xialotecon
  workers-limit: auto
  update-rate:
    currency:
      garbage: never
      store: immediate
    account:
      garbage: 5min
      store: 10s
    transaction:
      garbage: 30s
      store: immediate
...
