---
core:
  # Database configuration
  database:
    # The database type. "sqlite" and "mysql" are supported.
    type: sqlite

    # Edit these settings only if you choose "sqlite".
    sqlite:
      # The file name of the database in the plugin data folder.
      # You can also put an absolute path here.
      file: data.sqlite
    # Edit these settings only if you choose "mysql".
    mysql:
      host: 127.0.0.1
      # Avoid using the "root" user for security reasons.
      username: root
      password: ""
      schema: xialotecon
    # The maximum number of simultaneous SQL queries
    # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
    worker-limit: 1

  # About loading, saving and synchronizing
  # notify-changes: When some data are changed on this server, notify other servers about it.
  #   Set to false if you only use XialotEcon on this server, or if you are not using a shared database.
  # "garbage" and "store" are for more advanced users.
  # garbage: If some data aren't used for a long time, unload them from memory.
  #   recommended values:
  #     "never" only if there is a finite amount of them
  #       e.g. you won't have many currencies, but you will have many accounts as more players login
  #     "30s" if the data would not be used continuously
  #       e.g. accounts will be used continuously as the player stays online, but transactions will become unused very quickly
  #     "10min" if the data would be used continuously
  # store: The frequency of saving changes.
  #   recommended values:
  #     "1s" only if the data are rarely changed and the database is shared with other servers also running XialotEcon
  #       e.g. currency data consist of currency names and symbols, which are rarely changed.
  #       e.g. transaction is rarely changed once created. it is usually just accessed rather than changed.
  #     "3s" if the data may be frequently changed, and it has a long garbage time on other servers
  #       e.g. account has a long garbage time, and it is frequently changed (if the player pays/receives money), and the account may be accessed from other servers
  data-model:
    currency:
      garbage: never
      store: 1s
      notify-changes: true
    account:
      garbage: 10min
      store: 3s
      notify-changes: true
    transaction:
      garbage: 30s
      store: 1s
      notify-changes: true

  
...
