<?php

/*
 * libglocal message ID constant file
 *
 * This file is automatically generated by libglocal-def
 */

declare(strict_types=1);

namespace DHMO\XialotEcon;

final class Messages{
	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>XialotEcon</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_MAIN_TITLE = "xialotecon.kinetic.main.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Welcome to XialotEcon!</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_MAIN_SYNOPSIS = "xialotecon.kinetic.main.synopsis";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Personal</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_PLAYER_TITLE = "xialotecon.kinetic.player.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Manage your accounts</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_PLAYER_SYNOPSIS = "xialotecon.kinetic.player.synopsis";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Pay</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_PLAYER_PAY_TITLE = "xialotecon.kinetic.player.pay.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Pay another player</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_PLAYER_PAY_SYNOPSIS = "xialotecon.kinetic.player.pay.synopsis";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Whom to pay</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_PLAYER_PAY_TARGET_TITLE = "xialotecon.kinetic.player.pay.target.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Staff Tools</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_TITLE = "xialotecon.kinetic.staff.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Hello staff! What would you like to do?</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_SYNOPSIS = "xialotecon.kinetic.staff.synopsis";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Pending Queues</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_QUEUES_TITLE = "xialotecon.kinetic.staff.queues.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Some pending work to do.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_QUEUES_SYNOPSIS = "xialotecon.kinetic.staff.queues.synopsis";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Bankruptcy</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_QUEUES_BANKRUPTCY_TITLE = "xialotecon.kinetic.staff.queues.bankruptcy.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Players below are unable to repay debts automatically. Click into each player to view his financial status. Help them liquidate properties and carry out any additional action.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_QUEUES_BANKRUPTCY_SYNOPSIS = "xialotecon.kinetic.staff.queues.bankruptcy.synopsis";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Global Economy Analytics</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_TITLE = "xialotecon.kinetic.staff.analytics.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>network.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_SYNOPSIS = "xialotecon.kinetic.staff.analytics.synopsis";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Wealthiest Players</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_WEALTH_LIST_TITLE = "xialotecon.kinetic.staff.analytics.wealth-list.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Click into each player to view his financial status.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_WEALTH_LIST_SYNOPSIS = "xialotecon.kinetic.staff.analytics.wealth-list.synopsis";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>%{§c}You don't have permission to view other players' balance.</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_WEALTH_LIST_PERMISSION_MESSAGE_HIS = "xialotecon.kinetic.staff.analytics.wealth-list.permission-message.his";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>display size</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_WEALTH_LIST_LIMIT_ARG_NAME = "xialotecon.kinetic.staff.analytics.wealth-list.limit.arg-name";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Number of players to display</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_WEALTH_LIST_LIMIT_INPUT_NAME = "xialotecon.kinetic.staff.analytics.wealth-list.limit.input-name";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Currency weight</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_WEALTH_LIST_CURRENCY_WEIGHT_TITLE = "xialotecon.kinetic.staff.analytics.wealth-list.currency-weight.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Include ${currency.name}?</p>
	 * </blockquote>
	 * <h3>Arguments:</h3>
	 * - `currency.name`: string</li>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_WEALTH_LIST_CURRENCY_WEIGHT_TOGGLE = "xialotecon.kinetic.staff.analytics.wealth-list.currency-weight.toggle";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Weight:</p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_WEALTH_LIST_CURRENCY_WEIGHT_WEIGHT = "xialotecon.kinetic.staff.analytics.wealth-list.currency-weight.weight";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p>Balance of ${whose}</p>
	 * </blockquote>
	 * <h3>Arguments:</h3>
	 * - `whose`: string</li>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_BALANCE_TITLE = "xialotecon.kinetic.staff.analytics.balance.title";

	/**
	 * <h3>Base translation</h3>
	 * <blockquote>
	 *     <p> </p>
	 * </blockquote>
	 */
	public const XIALOTECON_KINETIC_STAFF_ANALYTICS_BALANCE_CONTENT = "xialotecon.kinetic.staff.analytics.balance.content";
}
